database:
  hosts: localhost
  name: frm
  test_name: frm_test
  w: 1     # Please see documentation of the Mongo
  j: True  # Please see documentation of the Mongo

redis:
  host: localhost
  port: 6379
  db: 0
  test_db: 1
